- url: 'https://elciudadanoweb.com/feed/'
- url: 'https://www.clarin.com/rss/lo-ultimo/'
- url: 'https://cenital.com/secciones/newsletters/off-the-record/feed/'
- url: 'https://cenital.com/secciones/newsletters/kohan/feed/'
